# Generated by Django 3.2 on 2021-04-20 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song', models.CharField(max_length=100)),
                ('duration', models.IntegerField()),
                ('upload_time', models.CharField(max_length=20)),
            ],
        ),
    ]
