# Generated by Django 3.2 on 2021-04-21 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='songs',
            name='upload_time',
        ),
    ]
