# Generated by Django 3.2 on 2021-04-21 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0002_remove_songs_upload_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='duration',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
