# Generated by Django 3.2 on 2021-04-21 13:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0003_alter_songs_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='songs',
            name='upload_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='songs',
            name='duration',
            field=models.IntegerField(null=True),
        ),
    ]
